application:
  map:
    ngii:
      apikey: 63AEED5B92651B793F4E3EC2A21B80A8
      url: https://map.ngii.go.kr/openapi/Gettile.do
      sub:
        url: http://210.117.198.120:8081/o2map/services
      cache:
        path: ~/kma-tilemap-cache/
    geoserver:
      url: http://220.90.239.149:8080/geoserver

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.101.211.71:5433/project?autoReconnect=true
    username: postgres
    password: A!S@d3f4g5
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  port: 9600
  error:
    include-stacktrace: always
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    session:
      timeout: 0